services:
  - type: web
    name: crypto-analysis
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      # تثبيت المكتبات الأساسية
      apt-get update
      apt-get install -y python3-dev build-essential wget git

      # تحميل TA-Lib المجمع مسبقاً من GitHub
      git clone https://github.com/TA-Lib/ta-lib.git
      cd ta-lib/
      ./configure --prefix=/usr
      make
      make install
      cd ..
      rm -rf ta-lib
      
      # تثبيت numpy أولاً
      pip install numpy==1.26.2
      
      # تثبيت TA-Lib Python
      export TA_LIBRARY_PATH=/usr/lib
      export TA_INCLUDE_PATH=/usr/include
      pip install --no-binary :all: TA-Lib==0.4.28
      
      # تثبيت باقي المتطلبات
      pip install -r requirements.txt
      
      # التحقق من التثبيت
      python -c "import talib; print('TA-Lib installed successfully')"
      
      # عرض محتويات المجلد
      echo "=== محتويات المجلد ==="
      ls -la
      
      # عرض المكتبات المثبتة
      echo "=== المكتبات المثبتة ==="
      pip list
    startCommand: |
      cd /opt/render/project/src
      export TA_LIBRARY_PATH=/usr/lib
      export TA_INCLUDE_PATH=/usr/include
      export LD_LIBRARY_PATH=/usr/lib
      gunicorn "main:app.server" --timeout 180 --workers 1 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TA_LIBRARY_PATH
        value: /usr/lib
      - key: TA_INCLUDE_PATH
        value: /usr/include
      - key: LD_LIBRARY_PATH
        value: /usr/lib
      - key: PYTHONPATH
        value: /opt/render/project/src
