services:
  - type: web
    name: crypto-analysis
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      # تثبيت المتطلبات الأساسية
      apt-get update
      apt-get install -y python3-dev build-essential wget

      # تحميل وتثبيت TA-Lib المجمع مسبقاً
      mkdir -p /tmp/ta-lib
      cd /tmp/ta-lib
      wget https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz
      tar -xvf ta-lib-0.4.0-src.tar.gz
      cd ta-lib/
      ./configure --prefix=/usr
      make
      sudo make install
      cd /opt/render/project/src
      
      # تثبيت numpy أولاً
      pip install numpy==1.26.2
      
      # تثبيت TA-Lib من الحزمة المجمعة مسبقاً
      pip install --no-cache-dir TA-Lib==0.4.28
      
      # تثبيت باقي المتطلبات
      pip install -r requirements.txt
      
      # التأكد من تثبيت TA-Lib
      python -c "import talib; print('TA-Lib version:', talib.__version__)"
      
    startCommand: gunicorn "main:app.server" --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LD_LIBRARY_PATH
        value: /usr/lib
      - key: PYTHONPATH
        value: /opt/render/project/src
