services:
  - type: web
    name: crypto-analysis
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      # تثبيت Miniconda
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      
      # تهيئة Conda
      conda init bash
      source ~/.bashrc
      
      # إنشاء بيئة Conda جديدة
      conda create -n myenv python=3.11 -y
      conda activate myenv
      
      # تثبيت TA-Lib من قناة conda-forge
      conda install -c conda-forge ta-lib -y
      
      # تثبيت باقي المتطلبات باستخدام pip
      pip install -r requirements.txt
      
      # التحقق من التثبيت
      python -c "import talib; print('TA-Lib installed successfully')"
      
    startCommand: |
      export PATH="$HOME/miniconda/bin:$PATH"
      source ~/.bashrc
      conda activate myenv
      gunicorn "main:app.server" --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
