services:
  - type: web
    name: crypto-analysis
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      # تثبيت المكتبات الأساسية
      apt-get update
      apt-get install -y python3-dev build-essential wget curl

      # تثبيت TA-Lib من مستودع Ubuntu
      curl -L https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/ta-lib_0.4.0-3_amd64.deb.html -o ta-lib.deb
      dpkg -i ta-lib.deb || true
      apt-get -f install -y
      
      # تثبيت numpy أولاً
      pip install numpy==1.26.2
      
      # تثبيت TA-Lib Python
      pip install TA-Lib==0.4.28
      
      # تثبيت باقي المتطلبات
      pip install -r requirements.txt
      
      # عرض المكتبات المثبتة للتأكد
      pip list | grep -i ta-lib
      
      # عرض محتويات المجلد
      echo "=== محتويات المجلد ==="
      ls -la
    startCommand: |
      cd /opt/render/project/src
      gunicorn "main:app.server" --timeout 180 --workers 1 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LD_LIBRARY_PATH
        value: /usr/lib
      - key: PYTHONPATH
        value: /opt/render/project/src
