services:
  - type: web
    name: crypto-analysis
    env: python
    buildCommand: |
      # تثبيت المتطلبات الأساسية
      apt-get update
      apt-get install -y wget build-essential

      # تحميل وتثبيت TA-Lib
      wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
      tar -xvf ta-lib-0.4.0-src.tar.gz
      cd ta-lib/
      ./configure --prefix=/usr
      make
      make install
      cd ..
      rm -rf ta-lib-0.4.0-src.tar.gz ta-lib/
      
      # تثبيت متطلبات Python
      pip install numpy
      pip install TA-Lib
      pip install -r requirements.txt
    startCommand: gunicorn main:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LD_LIBRARY_PATH
        value: /usr/lib
