services:
  - type: web
    name: crypto-analysis
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: LD_LIBRARY_PATH
        value: /usr/lib
