services:
  - type: web
    name: crypto-analysis
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      # تثبيت المكتبات الأساسية
      apt-get update
      apt-get install -y python3-dev build-essential wget

      # تحميل وتثبيت TA-Lib المجمع مسبقاً
      wget https://files.pythonhosted.org/packages/e3/13/88f50646c3e3eff2e6fb7c0a55c3bf44e5f37eff34e1e9b29d8a62c6e6a0/TA_Lib-0.4.28-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
      pip install TA_Lib-0.4.28-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

      # تثبيت باقي المتطلبات
      pip install -r requirements.txt
      
      # عرض المكتبات المثبتة للتأكد
      pip list | grep -i ta-lib
      
      # عرض محتويات المجلد
      echo "=== محتويات المجلد ==="
      ls -la
    startCommand: |
      cd /opt/render/project/src
      gunicorn "main:app.server" --timeout 180 --workers 1 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
