services:
  - type: web
    name: crypto-analysis
    env: python
    buildCommand: |
      # تثبيت المتطلبات الأساسية
      sudo apt-get update
      sudo apt-get install -y python3-dev
      
      # تحميل وتثبيت الحزمة المجمعة مسبقاً لـ TA-Lib
      wget https://files.pythonhosted.org/packages/0b/db/c85e12c91fc0f6c3e0e8f7572f089d5c6d5d93fbd6c4e22a4c6f65f69e20/TA_Lib-0.4.24-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
      pip install TA_Lib-0.4.24-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
      
      # تثبيت باقي المتطلبات
      pip install -r requirements.txt
    startCommand: gunicorn main:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
