services:
  - type: web
    name: crypto-analysis
    env: python
    buildCommand: |
      # تثبيت المتطلبات الأساسية
      sudo apt-get update
      sudo apt-get install -y build-essential wget pkg-config
      
      # تنزيل وتثبيت TA-Lib
      wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
      tar -xvzf ta-lib-0.4.0-src.tar.gz
      cd ta-lib/
      ./configure --prefix=/usr
      make
      sudo make install
      cd ..
      rm -rf ta-lib-0.4.0-src.tar.gz ta-lib/
      
      # تثبيت متطلبات Python
      python -m pip install --upgrade pip
      pip install wheel setuptools numpy
      
      # تثبيت TA-Lib من مصدر بديل
      pip install --index-url https://pypi.anaconda.org/ranaroussi/simple ta-lib
      
      # تثبيت باقي المتطلبات
      pip install -r requirements.txt
    startCommand: gunicorn main:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LD_LIBRARY_PATH
        value: /usr/lib
