services:
  - type: web
    name: crypto-analysis
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      # تثبيت حزم النظام المطلوبة
      apt-get update
      apt-get install -y gcc build-essential
      
      # تحميل وتثبيت TA-Lib
      wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
      tar -xzf ta-lib-0.4.0-src.tar.gz
      cd ta-lib/
      ./configure
      make
      make install
      cd ..
      rm -rf ta-lib-0.4.0-src.tar.gz ta-lib/
      ldconfig
      
      # تثبيت المتطلبات Python
      pip install --upgrade pip wheel setuptools numpy
      pip install -r requirements.txt
    startCommand: gunicorn "main:app.server" --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LD_LIBRARY_PATH
        value: /usr/local/lib:$LD_LIBRARY_PATH
      - key: PYTHONPATH
        value: /opt/render/project/src
